allowBuilds:
  esbuild: true
  workerd: true

patchedDependencies:
  image-size@2.0.2: patches/image-size@2.0.2.patch

auditConfig:
  ignoreGhsas:
    - GHSA-w3rx-r6r6-pgpr
    - GHSA-5p2g-fcmc-qvqq
    - GHSA-vfj7-8cjw-p6xm

overrides:
  sharp: ">=0.35.5"
  source-map-js: ">=1.2.2"
